version: '2'

services:

  api_app_tutorial:
    container_name: 'api_app_tutorial'
    image: node:12
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - '${API_DIRECTORY}/:/api'
    tty: true
    environment:
      DB_HOST: db
    depends_on:
      - "db"
    links:
      - db

  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata: